name: pipeline-master

on:
  push:
    branches-ignore:
      - master
      - develop
env:
  MAVEN_PUBLISHING_USER: ${{ github.actor }}
  MAVEN_PUBLISHING_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
  MAVEN_PUBLISHING_URL: https://maven.pkg.github.com/soffa-io/artifacts
  PRV_MAVEN_URL: https://maven.pkg.github.com/soffa-io/artifacts
  PRV_MAVEN_USER: ${{ github.actor }}
  PRV_MAVEN_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
  SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
  SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check branch
        run: gradle check

