name: internal-release

on:
  push:
    branches: [ develop,master ]

env:
  MAVEN_PUBLISHING_USER: ${{ github.actor }}
  MAVEN_PUBLISHING_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
  MAVEN_PUBLISHING_URL: https://maven.pkg.github.com/soffa-io/artifacts
  SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
  SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
  SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}

jobs:

  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run checks
        run: |
          echo ${{ github.ref }}
          gradle check
      - name: Publish artifact to Github
        if: ${{ github.ref == 'develp' }}
        run: gradle publish -x test -Dsnapshot=true




