name: pipeline-master

on:
  push:
    branches: [ master ]

jobs:
  publish-to-sonatype:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to sonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}
          SIGNING_SECRET_FILE: /tmp/gpg.secret
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode > /tmp/gpg.secret
          gradle sign publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository -PossrhUsername="$OSSRH_USERNAME" -PossrhPassword="$OSSRH_PASSWORD" -Psigning.keyId="$SIGNING_KEYID" -Psigning.password="$SIGNING_PASSWORD" -Psigning.secretKeyRingFile="/tmp/gpg.secret"

