name: pipeline-master

on:
  push:
    branches: [ master ]

jobs:

  release-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: gradle publish
        env:
          MVN_PUBLISHING_USER: ${{ env.GITHUB_ACTOR }}
          MVN_PUBLISHING_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}
          MVN_PUBLISHING_URL: https://maven.pkg.github.com/soffa/artifacts

  release-to-sonatype:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to sonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}
        run: |
          echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
          gradle sign publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository \
            -PossrhUsername=$SONATYPE_USERNAME \
            -PossrhPassword=$SONATYPE_PASSWORD \
            -Psigning.keyId=$SIGNING_KEYID  \
            -Psigning.password=$SIGNING_PASSWORD \
            -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg

