name: pipeline-master

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to sonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
          gradle publish -PmvnUsername=$MVN_USER -PmvnPassword=$MVN_PASSWORD -Prelease=true
          gradle sign publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository

