name: pipeline-master

on:
  push:
    branches: [ master ]

jobs:
  publish-to-sonatype:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to sonatype
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.OSSRH_SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          $SONATYPE_GPG: ${{ secrets.SOFFA_GPG_SIGNING_KEY }}
          SIGNING_SECRET_FILE: /tmp/gpg.secret
        run: |
          echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
          cat $HOME/.sonatype-keys.gpg
          gradle sign publishMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository \
            -PossrhUsername=$OSSRH_USERNAME \
            -PossrhPassword=$OSSRH_PASSWORD \
            -Psigning.keyId=$SIGNING_KEYID  \
            -Psigning.password=$SIGNING_PASSWORD \
            -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg

